# Generated by Django 4.1.7 on 2023-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('time', models.TimeField()),
                ('media', models.FileField(upload_to='media')),
            ],
        ),
    ]
